server:
  port: 9999
  run_mode: asc

postgres:
  uri: postgresql://fuck:you@db.wgrrgsmvfjxkdaglooiv.supabase.co:5432/postgres
  username: user
  password: pass
  host: localhost
  port: 5432
  database: db